# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  Beeder: http://beeder.me/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

#Weibo ID. e.g. 436062867 for http://weibo.com/436062867
weibo_id:  

# Duoshuo
duoshuo_shortname: 

# Baidu share
baidushare: false

#Back To Top
back_to_top: true

#Swiftype
Swiftype: true